### ISSUE TITLE
Map not showing up

### ISSUE THREAD

**Issue by Mandeep03** [q6112345/react-native-google-place-picker#11]
Hi, Thanks for the great package. Was just trying to integrate into one of my new project.
Everything configured, but seems the map is not showing up.
<img width="376" alt="screen shot 2016-12-16 at 8 54 30 pm" src="https://cloud.githubusercontent.com/assets/7822632/21267933/8be0482c-c3d2-11e6-8de5-755634e917ee.png">

**Comment by indesignlatam** [comment]
You have to enable Google Maps SDK for iOS on your google developer console

**Comment by Mandeep03** [comment]
Thank you so much @indesignlatam.
