### ISSUE TITLE
Move out of CocoaPods

### ISSUE THREAD

**Issue by burgalon** [q6112345/react-native-google-place-picker#15]
Currently when running `rnpm link`, Cocoapods are not installed or added, and so GoogleMaps.h and GooglePlaces.h is missing.
Is it easy to move this package to use `npm` instead of Cocoapods?

**Comment by zhangtaii** [comment]
@burgalon Sorry, It's too big to include all the dependencies in `npm package`, please check https://guides.cocoapods.org/using/getting-started.html to install `cocoapods` manually, then run`rnpm link` again.
