### ISSUE TITLE
Cannot read property show of undefined

### ISSUE THREAD

**Issue by GregTheGreek** [q6112345/react-native-google-place-picker#24]
followed instructions using npm link.

Used example from the provided 'full example' and this error occurred.

**Comment by benhylak** [comment]
Have this problem as well!

**Comment by frapsMatheus** [comment]
I'm having the same issue

**Comment by jakewtaylor** [comment]
+1, any solutions?

**Comment by bnap00** [comment]
still the same problem

**Comment by chrisnovak** [comment]
Did you provide a Google Maps API Key? For iOS in ``AppDelegate.m``:
```
#import <GoogleMaps/GoogleMaps.h>
#import <GooglePlaces/GooglePlaces.h>

NSString *kAPIKey = @"YOUR_API_KEY";
[GMSPlacesClient provideAPIKey:kAPIKey];
[GMSServices provideAPIKey:kAPIKey];
```

**Comment by chrisnovak** [comment]
Or, did you perhaps import like ``{ import RNGooglePlacePicker } from 'react-native-google-place-picker'`` instead of ``import RNGooglePlacePicker from 'react-native-google-place-picker'``?

**Comment by andaGS** [comment]
i'm having same issue,please help
