### ISSUE TITLE
Android Build Failure (with fix)

### ISSUE THREAD

**Issue by jakewtaylor** [q6112345/react-native-google-place-picker#25]
I got a build error when following the install steps for android:

```
[...]/node_modules/react-native-google-place-picker/android/src/main/java/com/reactlibrary/RNGooglePlacePickerPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
```
| Package | Version |
| --- | ---:|
| react-native | **0.47.2** |
| react-native-google-place-picker | **1.2.1** |

I've fixed it by simply removing the `@Override` in `RNGooglePlacePickerPackage.java` at line 20, which seems to be working fine. I would submit that change as a PR but I'm not confident enough that's a good fix, I don't know Java too well.

**Comment by ryanrossiter** [comment]
@jakewtaylor I think your solution works, at least one other project has done that to fix this issue: https://github.com/realm/realm-js/issues/1176

**Comment by jakewtaylor** [comment]
Looks like it's already been requested here: #28

**Comment by jakewtaylor** [comment]
Closing, fixed in https://github.com/zhangtaii/react-native-google-place-picker/pull/28
