### ISSUE TITLE
Error when building ( symbol(s) not found for architecture x86_64 )

### ISSUE THREAD

**Issue by tdurand** [q6112345/react-native-google-place-picker#3]
Hello, 

Thanks for your work. I have an issue while trying to run your example:

```
git clone git@github.com:q6112345/react-native-google-place-picker.git
cd react-native-google-place-picker/example
npm install
cd ios 
pod install
cd ..
react-native run-ios
```

I get this error: **symbol(s) not found for architecture x86_64** 

After some googling i found out i may be an issue with the compilation of C++ but was unable to solve it.

> **Undefined symbols for architecture x86_64**:
>   "std::__1::__next_prime(unsigned long)", referenced from:
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
>   "std::terminate()", referenced from:
>       ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
>   "operator delete[](void*)", referenced from:
>       -[RCTJSCExecutor dealloc] in libReact.a(RCTJSCExecutor.o)
>       executeRandomAccessModule(RCTJSCExecutor_, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
>       readRAMBundle(std::__1::unique_ptr<__sFILE, int (_)(__sFILE_)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
>       RandomAccessBundleData::~RandomAccessBundleData() in libReact.a(RCTJSCExecutor.o)
>   "operator delete(void_)", referenced from:
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::~__hash_table() in libReact.a(RCTJSCExecutor.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__deallocate(std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_>_) in libReact.a(RCTJSCExecutor.o)
>       std::__1::pair<std::__1::__hash_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_>_>, bool> std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__insert_unique<std::__1::pair<unsigned long const, unsigned long> const&>(std::__1::pair<unsigned long const, unsigned long> const&&&) in libReact.a(RCTJSCExecutor.o)
>       std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_> > > > std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__construct_node<std::__1::pair<unsigned long const, unsigned long> const&>(std::__1::pair<unsigned long const, unsigned long> const&&&) in libReact.a(RCTJSCExecutor.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::erase(std::__1::__hash_const_iterator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_>_>) in libReact.a(RCTJSCExecutor.o)
>   "operator new[](unsigned long)", referenced from:
>       executeRandomAccessModule(RCTJSCExecutor_, unsigned int, unsigned long, unsigned long) in libReact.a(RCTJSCExecutor.o)
>       readRAMBundle(std::__1::unique_ptr<__sFILE, int (_)(__sFILE_)>, RandomAccessBundleData&) in libReact.a(RCTJSCExecutor.o)
>   "operator new(unsigned long)", referenced from:
>       std::__1::unique_ptr<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_>, std::__1::__hash_node_destructor<std::__1::allocator<std::__1::__hash_node<std::__1::__hash_value_type<unsigned long, unsigned long>, void_> > > > std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__construct_node<std::__1::pair<unsigned long const, unsigned long> const&>(std::__1::pair<unsigned long const, unsigned long> const&&&) in libReact.a(RCTJSCExecutor.o)
>       std::__1::__hash_table<std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::__unordered_map_hasher<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::hash<unsigned long>, true>, std::__1::__unordered_map_equal<unsigned long, std::__1::__hash_value_type<unsigned long, unsigned long>, std::__1::equal_to<unsigned long>, true>, std::__1::allocator<std::__1::__hash_value_type<unsigned long, unsigned long> > >::__rehash(unsigned long) in libReact.a(RCTJSCExecutor.o)
>   "___cxa_begin_catch", referenced from:
>       ___clang_call_terminate in libReact.a(RCTJSCExecutor.o)
>   "___gxx_personality_v0", referenced from:
>       -[RCTJavaScriptContext initWithJSContext:onThread:] in libReact.a(RCTJSCExecutor.o)
>       -[RCTJavaScriptContext init] in libReact.a(RCTJSCExecutor.o)
>       -[RCTJavaScriptContext invalidate] in libReact.a(RCTJSCExecutor.o)
>       -[RCTJSCExecutor errorForJSError:] in libReact.a(RCTJSCExecutor.o)
>       RCTNSErrorFromJSError(RCTJSCWrapper_, OpaqueJSContext const_, OpaqueJSValue const_) in libReact.a(RCTJSCExecutor.o)
>       +[RCTJSCExecutor runRunLoopThread] in libReact.a(RCTJSCExecutor.o)
>       -[RCTJSCExecutor setBridge:] in libReact.a(RCTJSCExecutor.o)
>       ...
> ld: **symbol(s) not found for architecture x86_64**
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> 
> *\* BUILD FAILED **

**Comment by zhangtaii** [comment]
Try `⌘⌥⇧K`, or select Product > (Hold ⌥ Key) and select Clean Build Folder,
, if it not helps, you can check facebook/react-native#8880 to get more idea.

**Comment by tdurand** [comment]
Thanks, this did fix it: https://github.com/facebook/react-native/issues/8880#issuecomment-236994554
