### ISSUE TITLE
undefined is not an objects (evaluating '_reactNativeGooglePlacePicker2.default.show')

### ISSUE THREAD

**Issue by vishal-vaghasiya** [q6112345/react-native-google-place-picker#36]
![asset](https://user-images.githubusercontent.com/24429336/38862174-e6046190-4251-11e8-92f3-6f251038febd.png)

**Comment by aminosman** [comment]
@VKGraphics I am having this issue, how did you fix?

**Comment by andaGS** [comment]
i have same issue,please help

**Comment by Jayakumar92** [comment]
Hi thanks for the library, any update on this issue, It is still persisting.
