### ISSUE TITLE
Initial location

### ISSUE THREAD

**Issue by jamesholcomb** [q6112345/react-native-google-place-picker#4]
How do you specify the initial location?  In the simulator, the map always starts in the North Sea.

**Comment by zhangtaii** [comment]
You can not pass in a config for the viewport _currently_, which is not implemented yet.
The default map view is based on the device location.
**Workaround**: In iOS Simulator menu, go to Debug -> Location -> Custom Location.

**Comment by AndrewHenderson** [comment]
It would be great if you could provide an initial location. When editing an existing record with a location, I'd like to start the map at the already assigned location.
