### ISSUE TITLE
Please make it return response with 'Location title'.

### ISSUE THREAD

**Issue by spksoft** [q6112345/react-native-google-place-picker#6]
## Please make it return response with 'Location title'.

![image](https://cloud.githubusercontent.com/assets/1377991/20246078/be8bcf54-a9e1-11e6-8169-a72ca2bcad24.png)

## Now it just return address , lat and long

![image](https://cloud.githubusercontent.com/assets/1377991/20246087/e3096ad0-a9e1-11e6-8ebd-265bbf29c716.png)

**Comment by zhangtaii** [comment]
Thanks @ArthurAssuncao, that feature has been implemented on Android from https://github.com/q6112345/react-native-google-place-picker/pull/7, but It's still need to been done for iOS, any PR for that is welcome.

**Comment by zhangtaii** [comment]
Update:  @ArthurAssuncao killed the dragon, made it work for iOS https://github.com/q6112345/react-native-google-place-picker/pull/8, great work of him!
